name: CI
on:
  repository_dispatch:
    types: [containerregistry-imagepusheds]
    
# CONFIGURATION
# Set up the following secrets in your repository:
#
#   CLUST_NAME
#   RESOURCE_GROUP
env:
   CLUST_NAME: myvivekapp               #set this to your kubernetes cluster name
   RESOURCE_GROUP: webapptest1    #set this to your resource group name
   HOST_NAME: ${{ github.event.client_payload.data.request.host }}
   REPO_NAME: "${{ github.event.client_payload.data.request.host }}/${{ github.event.client_payload.data.target.repository }}"
   REPO_VERSION: "${{ github.event.client_payload.data.target.tag }}"
   IMAGE_NAME: "${{ github.event.client_payload.data.request.host }}/${{ github.event.client_payload.data.target.repository }}:${{ github.event.client_payload.data.target.tag }}"

   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    #- name: Check tag filter
     # run: |
      #  if [ "$repo_version" != "$filter" ]; then echo "incorrect tag filter supplied"; exit 1 ; fi;
          
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.HOST_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Set Web App ACR authentication
      uses: Azure/appservice-settings@v1
      with:
       app-name: 'node-rnc'
       app-settings-json: |
         [
             {
                 "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                 "value": "${{ secrets.REGISTRY_PASSWORD }}",
                 "slotSetting": false
             },
             {
                 "name": "DOCKER_REGISTRY_SERVER_URL",
                 "value": "${{ env.HOST_NAME }}",
                 "slotSetting": false
             },
             {
                 "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                 "value": "${{ secrets.REGISTRY_USERNAME  }}",
                 "slotSetting": false
             }
         ] 
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'node-rnc'
        images: "${{ env.IMAGE_NAME }}"
        startup-command: 'npm start'
